# Generated by Django 4.2.11 on 2025-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor')], max_length=10),
        ),
    ]
