# Generated by Django 4.2 on 2026-01-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('last_period_start', models.DateField(blank=True, help_text='First day of last period', null=True)),
                ('length_of_cycle', models.IntegerField(help_text='Average number of days between periods')),
                ('length_of_menses', models.IntegerField(help_text='How many days bleeding lasts')),
                ('mean_menses_length', models.IntegerField()),
                ('mean_bleeding_intensity', models.IntegerField(choices=[(1, 'Light'), (2, 'Moderate'), (3, 'Heavy')])),
                ('unusual_bleeding', models.BooleanField(default=False)),
                ('total_menses_score', models.IntegerField(choices=[(0, 'None'), (3, 'Mild'), (6, 'Moderate'), (9, 'Severe')])),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('predicted_next_period', models.DateField(blank=True, null=True)),
                ('estimated_ovulation_day', models.DateField(blank=True, null=True)),
                ('fertile_window_start', models.DateField(blank=True, null=True)),
                ('fertile_window_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
