# Generated by Django 4.2 on 2026-02-26 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_appointment_patient_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='Gynecologist', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
