# Generated by Django 4.2.19 on 2026-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_notification_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('message_received', 'Message Received'), ('emergency_alert', 'Emergency Alert'), ('profile', 'Profile'), ('settings_update', 'Settings Update'), ('system', 'System'), ('cycle', 'Cycle'), ('email', 'Email')], default='system', max_length=20),
        ),
    ]
