# Generated by Django 4.2.11 on 2026-01-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
