# Generated by Django 4.2 on 2026-02-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_appointment_cancel_reason_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_message',
            field=models.TextField(blank=True, help_text='Reason for appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Why doctor rejected'),
        ),
    ]
