# Generated by Django 4.2.11 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]